"""
Seed script: insert 40 quiz cards (15 OSPF, 15 BGP, 10 EIGRP).
Run with: python seed_quiz_data.py
"""
import asyncio
import os
import sys
from dotenv import load_dotenv

load_dotenv()

# Adjust path so we can import app modules
sys.path.insert(0, os.path.dirname(__file__))

from app.db import AsyncSessionLocal, create_tables
from app.models.models import QuizCard

CARDS = [
    # ── OSPF ──────────────────────────────────────────────────────────────────
    {
        "topic": "OSPF",
        "question": "What is the default OSPF hello interval on a broadcast network?",
        "answer": "10 seconds (dead interval 40 seconds)",
        "tags": ["ospf", "timers", "adjacency"],
    },
    {
        "topic": "OSPF",
        "question": "What causes two OSPF routers to be stuck in EXSTART/EXCHANGE state?",
        "answer": "MTU mismatch between neighbors. Fix with: ip ospf mtu-ignore, or match MTU on both sides",
        "tags": ["ospf", "troubleshooting", "adjacency"],
    },
    {
        "topic": "OSPF",
        "question": "What OSPF LSA type is generated by an ASBR?",
        "answer": "Type 5 (AS External LSA). Flooded throughout the OSPF domain except stub areas",
        "tags": ["ospf", "lsa", "redistribution"],
    },
    {
        "topic": "OSPF",
        "question": "In OSPF, what determines the DR/BDR election on a broadcast segment?",
        "answer": "Highest OSPF priority (default 1). Tiebreak: highest Router-ID. Priority 0 = never DR/BDR",
        "tags": ["ospf", "dr-bdr", "election"],
    },
    {
        "topic": "OSPF",
        "question": "What is the purpose of OSPF Area 0 (backbone area)?",
        "answer": "All inter-area routing must pass through Area 0. All areas must connect to Area 0 directly or via virtual link",
        "tags": ["ospf", "areas", "design"],
    },
    {
        "topic": "OSPF",
        "question": "What does 'ip ospf network point-to-point' do on an Ethernet interface?",
        "answer": "Disables DR/BDR election and treats the link as point-to-point. Faster convergence, no DR/BDR overhead",
        "tags": ["ospf", "network-type", "configuration"],
    },
    {
        "topic": "OSPF",
        "question": "What is an OSPF virtual link and when is it needed?",
        "answer": "A virtual link tunnels OSPF through a transit area to connect a discontiguous area to Area 0. Configured on ABRs: area X virtual-link <router-id>",
        "tags": ["ospf", "virtual-link", "design"],
    },
    {
        "topic": "OSPF",
        "question": "What is an OSPF stub area and what LSA types does it block?",
        "answer": "Blocks Type 5 (external) LSAs. ABR injects default route. All routers in area must have 'area X stub' configured",
        "tags": ["ospf", "stub-area", "lsa"],
    },
    {
        "topic": "OSPF",
        "question": "What is the difference between OSPF NSSA and a regular stub area?",
        "answer": "NSSA allows an ASBR inside the area to redistribute external routes as Type 7 LSAs. Regular stub blocks all external routes. Command: area X nssa",
        "tags": ["ospf", "nssa", "lsa"],
    },
    {
        "topic": "OSPF",
        "question": "What causes OSPF to remain in 2-WAY state instead of FULL?",
        "answer": "Normal for DROther-to-DROther on broadcast segments. DROther routers only form FULL adjacency with DR and BDR",
        "tags": ["ospf", "adjacency", "dr-bdr"],
    },
    {
        "topic": "OSPF",
        "question": "What is the OSPF router-id selection priority?",
        "answer": "1. Manually configured (router-id x.x.x.x) 2. Highest loopback IP 3. Highest active physical interface IP. Requires OSPF process restart to take effect",
        "tags": ["ospf", "router-id", "configuration"],
    },
    {
        "topic": "OSPF",
        "question": "How do you verify OSPF database LSAs?",
        "answer": "show ip ospf database - all LSAs\nshow ip ospf database router - Type 1\nshow ip ospf database network - Type 2\nshow ip ospf database external - Type 5",
        "tags": ["ospf", "verification", "lsa"],
    },
    {
        "topic": "OSPF",
        "question": "What OSPF command enables MD5 authentication on an interface?",
        "answer": "interface GigX\n ip ospf authentication message-digest\n ip ospf message-digest-key 1 md5 PASSWORD",
        "tags": ["ospf", "authentication", "security"],
    },
    {
        "topic": "OSPF",
        "question": "What is OSPF route summarization and where is it configured?",
        "answer": "Inter-area: on ABR 'area X range network mask'. External: on ASBR 'summary-address network mask'. Summarization reduces LSA flooding and routing table size",
        "tags": ["ospf", "summarization", "design"],
    },
    {
        "topic": "OSPF",
        "question": "What is the OSPF cost formula and default reference bandwidth?",
        "answer": "Cost = Reference BW / Interface BW. Default reference = 100 Mbps. FastEthernet and above all get cost 1. Change with: auto-cost reference-bandwidth <Mbps>",
        "tags": ["ospf", "metric", "cost"],
    },
    # ── BGP ──────────────────────────────────────────────────────────────────
    {
        "topic": "BGP",
        "question": "What is the difference between eBGP and iBGP?",
        "answer": "eBGP: between different AS numbers, TTL=1 (direct link), changes next-hop. iBGP: same AS, TTL=255, preserves next-hop, requires full mesh or RR",
        "tags": ["bgp", "ebgp", "ibgp"],
    },
    {
        "topic": "BGP",
        "question": "Why does iBGP require a full mesh by default?",
        "answer": "BGP split-horizon rule: iBGP routes learned from one iBGP peer cannot be advertised to another iBGP peer. Full mesh ensures all routers receive all routes",
        "tags": ["bgp", "ibgp", "full-mesh"],
    },
    {
        "topic": "BGP",
        "question": "What is a BGP Route Reflector?",
        "answer": "Eliminates iBGP full mesh requirement. RR reflects routes from clients to other clients and non-clients. Configured with: neighbor X route-reflector-client",
        "tags": ["bgp", "route-reflector", "scalability"],
    },
    {
        "topic": "BGP",
        "question": "What are the first 5 steps of BGP best path selection?",
        "answer": "1. Highest Weight (local, Cisco-proprietary)\n2. Highest Local Preference\n3. Locally originated (network/aggregate/redistribute)\n4. Shortest AS Path\n5. Lowest Origin (IGP < EGP < Incomplete)",
        "tags": ["bgp", "best-path", "attributes"],
    },
    {
        "topic": "BGP",
        "question": "What does 'neighbor X next-hop-self' do and when is it needed?",
        "answer": "Sets the BGP next-hop to the local router's update-source address. Needed in iBGP when eBGP next-hop addresses are not reachable within the AS",
        "tags": ["bgp", "next-hop", "ibgp"],
    },
    {
        "topic": "BGP",
        "question": "What causes BGP to be stuck in ACTIVE state?",
        "answer": "Cannot establish TCP connection to peer (port 179). Check: IP reachability, ACLs blocking TCP/179, correct neighbor IP, ebgp-multihop if not directly connected",
        "tags": ["bgp", "troubleshooting", "adjacency"],
    },
    {
        "topic": "BGP",
        "question": "What is AS path prepending and when do you use it?",
        "answer": "Artificially lengthens the AS_PATH by repeating your own AS number. Makes route less preferred to external peers. Used for inbound traffic engineering with multiple upstream providers",
        "tags": ["bgp", "as-path", "traffic-engineering"],
    },
    {
        "topic": "BGP",
        "question": "What is the BGP community attribute and give two well-known values?",
        "answer": "32-bit tag for grouping routes and applying policy. Well-known: no-export (0xFFFFFF01) - don't advertise outside AS; no-advertise (0xFFFFFF02) - don't advertise to any peer",
        "tags": ["bgp", "community", "policy"],
    },
    {
        "topic": "BGP",
        "question": "What is the difference between Local Preference and MED?",
        "answer": "Local Preference: used within AS to influence outbound path (higher=better, default 100). MED: sent to external peers to influence inbound path (lower=better, default 0)",
        "tags": ["bgp", "local-pref", "med", "attributes"],
    },
    {
        "topic": "BGP",
        "question": "What command activates a BGP neighbor for IPv4 unicast?",
        "answer": "router bgp <AS>\n address-family ipv4 unicast\n  neighbor X.X.X.X activate",
        "tags": ["bgp", "configuration", "address-family"],
    },
    {
        "topic": "BGP",
        "question": "What is BGP soft reset and why is it needed?",
        "answer": "Applies new BGP policy without resetting the TCP session. Inbound: 'clear ip bgp X soft in' (requires route-refresh capability). Outbound: 'clear ip bgp X soft out'",
        "tags": ["bgp", "soft-reset", "policy"],
    },
    {
        "topic": "BGP",
        "question": "What is the purpose of 'bgp additional-paths'?",
        "answer": "Allows advertising multiple paths for the same prefix (add-path). Improves convergence and provides backup paths. Used with route reflectors in large networks",
        "tags": ["bgp", "add-path", "convergence"],
    },
    {
        "topic": "BGP",
        "question": "How do you advertise a network in BGP?",
        "answer": "1. network command: 'network X.X.X.X mask Y.Y.Y.Y' - prefix must exist in routing table\n2. redistribute from IGP\n3. aggregate-address for summarization",
        "tags": ["bgp", "network", "advertisement"],
    },
    {
        "topic": "BGP",
        "question": "What is eBGP multihop and when do you configure it?",
        "answer": "Allows eBGP peering between non-directly-connected routers by increasing TTL. 'neighbor X ebgp-multihop N'. Required for loopback-to-loopback eBGP peering",
        "tags": ["bgp", "ebgp-multihop", "configuration"],
    },
    {
        "topic": "BGP",
        "question": "What is BGP confederations and how does it compare to route reflectors?",
        "answer": "Splits large AS into sub-ASes. eBGP runs between sub-ASes (looks like iBGP externally). More complex than RR but better loop prevention. Used in very large SP networks",
        "tags": ["bgp", "confederations", "scalability"],
    },
    # ── EIGRP ──────────────────────────────────────────────────────────────────
    {
        "topic": "EIGRP",
        "question": "What are EIGRP K values and their defaults?",
        "answer": "K1=1 (Bandwidth), K2=0 (Load), K3=1 (Delay), K4=0 (Reliability), K5=0. Composite metric = 256*(K1*(10^7/min_BW) + K3*(sum_delay/10))",
        "tags": ["eigrp", "metric", "k-values"],
    },
    {
        "topic": "EIGRP",
        "question": "What is the EIGRP Feasibility Condition?",
        "answer": "A neighbor's Reported Distance (RD) must be less than the local Feasibility Distance (FD). Guarantees loop-free alternate paths. Feasible Successors are stored in topology table as instant backup",
        "tags": ["eigrp", "feasibility-condition", "topology"],
    },
    {
        "topic": "EIGRP",
        "question": "What is the difference between Successor and Feasible Successor?",
        "answer": "Successor: best path (lowest FD), installed in routing table. Feasible Successor: backup path meeting FC, in topology table only. If successor fails, FS promotes instantly without re-query",
        "tags": ["eigrp", "successor", "feasible-successor"],
    },
    {
        "topic": "EIGRP",
        "question": "What causes EIGRP to go Stuck in Active (SIA)?",
        "answer": "Router sends Query but doesn't receive Reply within active timer (3 min default). Usually: link failure, router down, insufficient resources. Fix with: eigrp stub, summarization to limit query scope",
        "tags": ["eigrp", "sia", "troubleshooting"],
    },
    {
        "topic": "EIGRP",
        "question": "What is EIGRP variance and how does it work?",
        "answer": "Enables unequal-cost load balancing. 'variance N' - routes with FD up to N × successor FD are installed. Traffic load-balanced proportionally to metric. Default variance=1 (equal-cost only)",
        "tags": ["eigrp", "variance", "load-balancing"],
    },
    {
        "topic": "EIGRP",
        "question": "What happens with EIGRP K-value mismatch?",
        "answer": "Neighbor relationship will NOT form. Error message: 'K-value mismatch'. All K-values must match between neighbors. Check with: show ip eigrp neighbors",
        "tags": ["eigrp", "k-values", "troubleshooting"],
    },
    {
        "topic": "EIGRP",
        "question": "What is EIGRP stub routing?",
        "answer": "Spoke router ('eigrp stub connected summary') only advertises connected/summary routes. Hub will not send Queries to stub routers, dramatically reducing query scope and SIA incidents",
        "tags": ["eigrp", "stub", "design"],
    },
    {
        "topic": "EIGRP",
        "question": "How do you summarize routes in EIGRP?",
        "answer": "Per-interface: 'ip summary-address eigrp <AS> <network> <mask>'. Suppresses component routes, advertises only summary. Generates a Null0 route locally for loop prevention",
        "tags": ["eigrp", "summarization", "configuration"],
    },
    {
        "topic": "EIGRP",
        "question": "What command shows EIGRP topology including all paths?",
        "answer": "show ip eigrp topology - shows successors and feasible successors\nshow ip eigrp topology all-links - shows ALL paths including those not meeting FC",
        "tags": ["eigrp", "verification", "topology"],
    },
    {
        "topic": "EIGRP",
        "question": "What is EIGRP named mode and its advantages?",
        "answer": "router eigrp NAME + address-family ipv4 unicast autonomous-system X. Advantages: supports multiple address families, per-AF configuration, per-interface parameters, recommended for new deployments",
        "tags": ["eigrp", "named-mode", "configuration"],
    },
]


async def seed():
    await create_tables()

    async with AsyncSessionLocal() as session:
        # Check if already seeded
        from sqlalchemy import select, func
        from app.models.models import QuizCard as QC
        count_result = await session.execute(select(func.count(QC.id)))
        count = count_result.scalar()

        if count and count > 0:
            print(f"Database already has {count} cards. Skipping seed.")
            return

        for card_data in CARDS:
            card = QuizCard(
                topic=card_data["topic"],
                question=card_data["question"],
                answer=card_data["answer"],
                tags=card_data["tags"],
            )
            session.add(card)

        await session.commit()
        print(f"Seeded {len(CARDS)} quiz cards successfully.")
        print(f"  OSPF: {sum(1 for c in CARDS if c['topic'] == 'OSPF')}")
        print(f"  BGP: {sum(1 for c in CARDS if c['topic'] == 'BGP')}")
        print(f"  EIGRP: {sum(1 for c in CARDS if c['topic'] == 'EIGRP')}")


if __name__ == "__main__":
    asyncio.run(seed())
